### ISSUE TITLE
Code for Chapter 2 iplot graph does not fill in.

### ISSUE THREAD

**Issue by CarterFitz** [PacktPublishing/Python-for-Finance-Cookbook#2]

**Comment by CarterFitz** [comment]
Eryk, After using your workaround on the Chapter 2 signal code it worked perfectly the first time.  However, on the remaining attempts the iplot graph does not fill in and the code does not give any error.  Any suggestions?

**Comment by erykml** [comment]
Hi Carter, 

Could you try the solution proposed [here](https://stackoverflow.com/questions/51098041/backtrader-graph-plots-in-jupiter-notebook-disappear-when-re-running-cell)?
Hope it solves your problems :)

**Comment by CarterFitz** [comment]
Eryk,
Thanks again for your help.  It seems from my research that something in
ploty is not functioning properly and therefore iplot is not working.  I
will use some plot other than iplot for now.

Well, I am spending the day on your book.
Thanks.
Carter

**Comment by erykml** [comment]
Hi Carter, 

The problem is most likely not with `plotly`, but with `iplot`, which is an interactive plot generated via `matplotlib`. What you can always do is run the separate `.py` files and they will generate the plots as well. Or try the solution provided in the previous message for making it work in Jupyter. 

Hope it will work out for you :)
