### ISSUE TITLE
cufflinks go offline

### ISSUE THREAD

**Issue by nickdesaulniers** [PacktPublishing/Python-for-Finance-Cookbook#5]
Hi, I really like your book! Great concise examples with modern libraries.

Working through chpt 2 building the dashboard, it seems that I need to add `cf.go_offline()` otherwise the plot is never generated, and the call to `qf.iplot()` hangs in some retry loop that's trying to send an HTTP request to plotly.  I suspect this API changed since the book was published?

**Comment by nickdesaulniers** [comment]
via: https://nbviewer.jupyter.org/gist/santosjorge/5fdbe947496faf7af5e6

**Comment by erykml** [comment]
Thanks for the kind words @nickdesaulniers! I am glad you like it :) 

Thanks for bringing that to my attention, I am not sure if it was caused by the change in the API or the fact that I might have initially changed the settings using `cf.set_config_file(offline=True)`, what made me skip the `cf.go_offline()`. Either way, I added the missing part to Notebook. Once again, thanks for mentioning this!
